---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      initContainers:
        - name: redis-pvc-deployment
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z $REDIS_HOST $REDIS_PORT; do
                echo "Waiting for Redis server at $REDIS_HOST:$REDIS_PORT...";
                sleep 2;
              done;
          env:
            - name: REDIS_HOST
              value: "planetarysystems-redis-service"
            - name: REDIS_PORT
              value: "6379"
      containers:
        - name: flask-app
          imagePullPolicy: Always
          image: arshansani/flask_app:1.0
          command: [python3, src/api.py]
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "planetarysystems-redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: LOG_LEVEL
              value: "DEBUG"
