---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker
          imagePullPolicy: Always
          image: username/worker:1.0
          command: [python3, worker.py]
          env:
            - name: REDIS_HOST
              value: "Planetary_Systems-redis-service"
